# SPDX-FileCopyrightText: Copyright © 2024 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-License-Identifier: MPL-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ^cmake/patches/
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/flake8/
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [-c, .bandit]
  - repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.1
    hooks:
      - id: reuse
