version = 1
SPDX-PackageName = "pygafro"
SPDX-PackageSupplier = "Philip Abbet philip.abbet@idiap.ch"
SPDX-PackageDownloadLocation = "https://github.com/idiap/pygafro"

[[annotations]]
path = "colcon.pkg"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2024 Idiap Research Institute <contact@idiap.ch>"
SPDX-License-Identifier = "MPL-2.0"
